import Head from "next/head";
import { Advantages } from "../components/advantages";
import { Banner } from "../components/banner";
import { CutYourself } from "../components/cut-yourself";
import { Header } from "../components/header";
import { HowSaleHair } from "../components/how-sale-hair";
import { OnlineEvaluation } from "../components/online-evaluation";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header></Header>

			<main>
				<Banner />
				<HowSaleHair />
				<Advantages />
				<OnlineEvaluation />
				<CutYourself />
			</main>

			<footer>d</footer>
		</div>
	);
}
