import Head from "next/head";
import { Advantages } from "../components/main/advantages.jsx";
import { AskSection } from "../components/main/ask-section";
import { Banner } from "../components/main/banner";
import { CutYourself } from "../components/main/cut-yourself";
import { Footer } from "../components/footer";
import { Header } from "../components/header";
import { HowSaleHair } from "../components/main/how-sale-hair";
import { MapSection } from "../components/main/map-section";
import { OnlineEvaluation } from "../components/main/online-evaluation";
import { ReviewsSection } from "../components/main/reviews-section";
import { ToClientSection } from "../components/main/to-client-section";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header></Header>

			<main>
				<Banner />
				<HowSaleHair />
				<Advantages />
				<OnlineEvaluation />
				<CutYourself />
				<ToClientSection />
				<ReviewsSection />
				<AskSection />
				<MapSection />
			</main>

			<Footer />
		</div>
	);
}
