import Head from "next/head";
import { Advantages } from "../components/main/advantages.jsx";
import { AskSection } from "../components/main/ask-section";
import { Banner } from "../components/main/banner";
import { CutYourself } from "../components/main/cut-yourself";
import { Footer } from "../components/footer";
import { Header } from "../components/header";
import { HowSaleHair } from "../components/main/how-sale-hair";
import { MapSection } from "../components/main/map-section";
import { OnlineEvaluation } from "../components/main/online-evaluation";
import { ReviewsSection } from "../components/main/reviews-section";
import { ToClientSection } from "../components/main/to-client-section";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Купить волосы Гродно</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link
					href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<Header></Header>

			<main>
				<Banner />
				<HowSaleHair />
				<Advantages />
				<OnlineEvaluation />
				<CutYourself />
				<ToClientSection />
				<ReviewsSection />
				<AskSection />
				<MapSection />
			</main>

			<Footer />
		</div>
	);
}
